FROM ubuntu:latest

RUN apt-get -y update 
RUN apt-get -y install git

RUN git clone https://sundayheathers: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@github.com/InzynieriaOprogramowaniaAGH/MDO2023_S.git

